version: '3.4'

services:
  salesservice:
    image: ${DOCKER_REGISTRY-}salesservice
    build:
      context: .
      dockerfile: SalesService/Dockerfile

  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=pgxledejos
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
 
  mongodb:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    ports:
    - 27017:27017
    volumes:
    - mongodata:/var/lib/mongodb/data

volumes:
  pgdata:
  mongodata:  